spring:
  application:
    name: TaskManagementAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/task_management
    username: task_user
    password: t#sk_user_123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # Use 'update' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

jwt:
  secret: mySecretKey
  expiration: 86400000 # 24 hours
  refresh-expiration: 2592000000 # 30 days

app:
  cors:
    allowed-origins: http://localhost:4200
