spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}

app:
  cors:
    allowed-origins: ${FRONTEND_URL}

logging:
  level:
    com.taskmanagement: INFO
    org.springframework.security: INFO
